languageCode = "en"
languageName = "English"
displayName = "EN"
isoCode = "en"
weight = 1
rtl = false

title = "VictoryLuode"
logo = "img/VLC.png"
description = "A powerful, lightweight theme for Hugo built with Tailwind CSS."
# copyright = "Copy, _right?_ :thinking_face:"

dateFormat = "2 January 2006"

[author]
  name = "VictoryLuode"
  image = "img/VictoryLuodeProf.png"
  headline = "A powerful, lightweight theme for Hugo built with Tailwind CSS."
  bio = "CG Artist"
  links = [
  { email = "mailto:victoryluode@outlook.com" },
  { bilibili = "https://space.bilibili.com/176090455?spm_id_from=333.1007.0.0" },
  { instagram = "https://www.instagram.com/victoryluode/" },
  { artstation = "https://www.artstation.com/victoryluode" },
  { twitter = "https://twitter.com/VictoryLuode" },
  { youtube = "https://www.youtube.com/victoryluode" },
]
