languageCode = "zh-cn"
languageName = "English"
displayName = "EN"
isoCode = "zh-cn"
weight = 1
rtl = false

title = "VictoryLuode"
# logo = "img/logo.png"
description = "My awesome website"
# copyright = "Copy, _right?_ :thinking_face:"

dateFormat = "2 January 2006"

[author]
  name = "VictoryLuode"
  image = "img/VictoryLuodeProf.png"
  headline = "I'm only human"
  bio = "A little bit about you"
  links = [
     { email = "mailto:victoryluode@outlook.com" },
     { bilibili = "https://space.bilibili.com/176090455?spm_id_from=333.1007.0.0" },
     { instagram = "https://www.instagram.com/victoryluode/" },
     { artstation = "https://www.artstation.com/victoryluode" },
     { twitter = "https://twitter.com/VictoryLuode" },
     { youtube = "https://www.youtube.com/victoryluode" },
  ]
